"""Add sector baselines and exit multiples

Revision ID: b247bffb2fdb
Revises: d99ad3d63bdb
Create Date: 2026-06-14 22:16:10.658286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b247bffb2fdb'
down_revision: Union[str, Sequence[str], None] = 'd99ad3d63bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
