"""Add risk_adjustment_rules table

Revision ID: d0f28b3cebd5
Revises: b1768ab84eeb
Create Date: 2026-06-14 23:26:15.759615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f28b3cebd5'
down_revision: Union[str, Sequence[str], None] = 'b1768ab84eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
